# CREATE DATABASE STUDENTS;
# USE STUDENTS;

CREATE TABLE IF NOT EXISTS STUDENTS_TBL
   (
   ID int(11) NOT NULL AUTO_INCREMENT,
   FAKNO int(7),
   NAME VARCHAR(12),
   FAM  VARCHAR(15),
   ADDRESS VARCHAR(33),
   PRIMARY KEY(ID)
   )ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9;

INSERT INTO STUDENTS_TBL (ID, FAKNO, NAME, FAM, ADDRESS) VALUES
(1, 695390, 'Muncho', 'Veliki', 'bul. Ruski 82'),
(2, 617213, 'Suljo', 'Puljov', 'ul. Raponska 23'),
(3, 590380, 'Radka', 'Piratkova', 'ul. Chaka Raka 12');


CREATE TABLE IF NOT EXISTS SUBJECTS_TBL
   (
   ID int(11) NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(12),
   PRIMARY KEY(ID)
   )ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5;

INSERT INTO SUBJECTS_TBL (ID, NAME) VALUES
(1, 'OOP'),
(2, 'PIK3'),
(3, 'CP'),
(4, 'EP'),
(5, 'XML');

CREATE TABLE IF NOT EXISTS NOTES_TBL
   (
   ID int(11) NOT NULL AUTO_INCREMENT,
   STID INTEGER,
   SBID INTEGER,
   NOTE INTEGER,
   PRIMARY KEY(ID)
   )ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9;

INSERT INTO NOTES_TBL (ID, STID, SBID, NOTE) VALUES
(1, 1, 1, 3),
(2, 1, 2, 2),
(3, 1, 3, 5),

(4, 2, 5, 6),
(5, 2, 2, 2),
(6, 2, 1, 5),
(7, 2, 3, 5),

(8,  1, 1, 3),
(9,  1, 2, 2);


